baseurl      = "https://pazyp.github.io/"
title        = "pazikas.com"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

# Enable theme toggle
# 
# This options enables the theme toggle for the theme. 
# Per default, this option is off. 
# The theme is respecting the prefers-color-scheme of the operating systeme. 
# With this option on, the page user is able to set the scheme he wants. 
enableThemeToggle = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/PazyP"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/andrewpazikas/"

[[params.social]]
  name = "github"
  url = "https://github.com/pazyp"

  # Subtitle for home
  homeSubtitle = "A Place for things"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Andrew Pazikas"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"